const posts = [
  { id: 1,
  title: 'Einride brings its electric self driving trucks to the UAE', 
 author: 'Admin' ,
 number:3,
  date:"2023-05-30",
  },
  { id: 2,
    title: 'AI powered Personal Assistant for Windows', 
   author: 'Admin' ,
   number:1,
    date:"2023-05-30",
    },
    { id: 3,
      title: 'Start a Podcast and Build a Loyal Audience in No Time', 
     author: 'Admin' ,
     number:9,
      date:"2023-05-30",
      },
      { id: 4,
        title: 'National Parks in California, A Guide for Nature Lovers', 
       author: 'Admin' ,
       number:5,
        date:"2023-05-30",
        },
        { id: 5,
          title: ' Secrets of Successful Entrepreneurs You Need to Know', 
         author: 'Admin' ,
         number:8,
          date:"2023-05-30",
          },
          { id: 6,
            title: ' Start a Podcast and Build a Loyal Audience in No Time', 
           author: 'Admin' ,
           number:1,
            date:"2023-05-30",
            },
            { id: 7,
              title: ' C# 11, The Latest and Greatest Features with Code Examples', 
             author: 'Admin' ,
             number:1,
              date:"2023-05-30",
              },
              { id: 8,
                title: ' Secrets of Successful Entrepreneurs You Need to Know', 
               author: 'Admin' ,
               number:8,
                date:"2023-05-30",
                },
              { id: 9,
                title: 'National Parks in California, A Guide for Nature Lovers', 
                 author: 'Admin' ,
                 number:5,
                date:"2023-05-30",
                  },
                { id: 10,
                  title: 'AI powered Personal Assistant for Windows', 
                  author: 'Admin' ,
                  number:1,
                  date:"2023-05-30",
                 },
];
  export default posts;
